version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build React App
          command: npm run build

  deploy:
    docker:
      - image: docker:19.03.12
    steps:
      - setup_remote_docker:
          version: 19.03.12
      - run:
          name: Build and Publish Docker Image
          command: |
            docker build -t your-image-name .
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker tag your-image-name "$DOCKER_USERNAME/your-image-name:latest"
            docker push "$DOCKER_USERNAME/your-image-name:latest"
