version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: docker:19.03.12
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: npm install
      - run: npm run build

      - run:
          name: Build Docker Image
          command: |
            docker build -f Dockerfile -t fileupload .

      - run:
          name: Deploy Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push "$DOCKER_USERNAME/fileupload:latest"

workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master
