version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build React App
          command: npm run build

      - run:
          name: Build and Publish Docker Image
          command: |
            docker build -t "$DOCKER_USERNAME/fileupload:latest" -f ./Dockerfile ..
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push "$DOCKER_USERNAME/fileupload:latest"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy
