version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:16
    working_directory: /home/circleci/verity/web
    resource_class: large
    steps:
      - checkout:
          path: /home/circleci/verity/web
      - setup_remote_docker:
          version: 19.03.12
      - run: npm install
      - run: npm run build

      - run:
          name: Build Docker Image
          command: |
            docker build -t fileupload .

      - run:
          name: Deploy Docker Image
          command: |
            docker run -d -p 0.0.0.0:8000:8000 --name fileupload-container fileupload
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker tag fileupload "$DOCKER_USERNAME/fileupload:latest"
            docker push "$DOCKER_USERNAME/fileupload:latest"

workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master
